#this is workflow name
name: Hello workflow

#runs on a trigger
on:
  push:
    branches: [main]

#this are jobs inside the workflow
jobs:

#this is the name of the job
  greet:
  #this is github runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"

  details:
    run-on: ubuntu-latest
    steps:
      - name: version of python, docker
        run: docker --version && python --version
